### PR TITLE
Reorganize packages, reformat code.

### PR DESCRIPTION
**Pull request by brndnmtthws**
This is a code reorg to reflect that the project is no longer owned by Airbnb.

cc @elingg

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Okay, I can do that instead. I went with github because the project is hosted on github.

**Comment by brndnmtthws** [comment]
Actually, `org.mesos` doesn't really make sense since mesos.org doesn't exist. I'd rather just leave it like this.

**Comment by brndnmtthws** [comment]
Okay, I changed it to `org.apache.mesos.chronos`, which is a bit verbose for my liking, but it should suffice.

**Comment by elingg** [comment]
Thank you! :+1:

**Pull request merged**
