### PR TITLE
handle skip calculation on zero repeat schedule

### LINKED ISSUE #648: Division by zero in Chronos when scheduling a zero repeat schedule.
Mar  4 20:57:32 chronos[27641]: [2016-03-04 20:57:32,173] WARN Skipped forward 1 iterations, modified start from 'Thursday, March 3, 2016' to 'Friday, March 4, 2016 (org.apache.mesos.chronos.scheduler.jobs.JobUtils$:122)
Mar  4 20:57:32 chronos[27641]: [2016-03-04 20:57:32,174] WARN Skipped forward 1 iterations, modified start from 'Thursday, March 3, 2016' to 'Friday, March 4, 2016 
Mar  4 20:57:32 chronos[27641]: [2016-03-04 20:57:32,190] WARN Skipped forward 1 iterations, modified start from 'Thursday, March 3, 2016' to 'Friday, March 4, 2016 (org.apache.mesos.chronos.scheduler.jobs.JobUtils$:122)
Mar  4 20:57:32 chronos[27641]: [2016-03-04 20:57:32,192] ERROR Loading tasks or jobs failed. Exiting. (org.apache.mesos.chronos.scheduler.jobs.JobScheduler:605)
Mar  4 20:57:32 chronos[27641]: java.lang.ArithmeticException: / by zero

### PR DESCRIPTION
**Pull request by schneidexe**
This PR will fix #648

### CODE REVIEW

**Comment by bfoussier** [comment]
Hi,

I met the problem when doing HA tests. When chronos restarts it reloads jobs stored in Zookeeper (job was  { "schedule": "R//P", "name": "create-volume-flocker-demo", "command"...}, ) and fails.

I applied the fix you propose and now Chronos  loops infinitely : 
[2016-07-20 09:21:49,968] INFO Calling next for stream: R/2016-07-18T09:38:44.236Z/PT0S, jobname: create-volume-flocker-demo (org.apache.mesos.chrono\
s.scheduler.jobs.JobScheduler:509)
[2016-07-20 09:21:49,968] INFO JobNotificationObserver does not handle JobSkipped(ScheduleBasedJob(R/2016-07-18T09:38:44.236Z/PT0S,create-volume-floc\
ker-demo,docker volume create -d flocker --name apache_vol_2_staging -o size=45GB,PT60S,0,0,,,,2,,,,,,false,0.1,256.0,128.0,false,0,ListBuffer(),List\
Buffer(),false,root,null,,ListBuffer(),true,ListBuffer(),false,false,ListBuffer()),2016-07-18T09:38:44.236Z) (org.apache.mesos.chronos.scheduler.jobs\
.JobsObserver$:27)
[2016-07-20 09:21:49,968] INFO JobStats does not handle JobSkipped(ScheduleBasedJob(R/2016-07-18T09:38:44.236Z/PT0S,create-volume-flocker-demo,docker\
 volume create -d flocker --name apache_vol_2_staging -o size=45GB,PT60S,0,0,,,,2,,,,,,false,0.1,256.0,128.0,false,0,ListBuffer(),ListBuffer(),false,\
root,null,,ListBuffer(),true,ListBuffer(),false,false,ListBuffer()),2016-07-18T09:38:44.236Z) (org.apache.mesos.chronos.scheduler.jobs.JobsObserver$:\
27)
[2016-07-20 09:21:49,968] INFO tail: R/2016-07-18T09:38:44.236Z/PT0S now: 2016-07-20T09:21:48.145Z (org.apache.mesos.chronos.scheduler.jobs.JobSchedu\
ler:563)

and it restarts for same job.

[2016-07-20 09:21:49,968] INFO Calling next for stream: R/2016-07-18T09:38:44.236Z/PT0S, jobname: create-volume-flocker-demo (org.apache.mesos.chrono\
s.scheduler.jobs.JobScheduler:509)


Do I need another fix ?
Does the proposed fix prevent from storing corrupted data in Zookeeper ?
Are my data corrupted in Zookeeper and should I erase them ?

**Comment by schneidexe** [comment]
Do you use the code from master or 2.4.0? I used it with master.

For me the fix solved that issue. I might be a problem when you have the data already in zookeeper. It does no fix corrupt data in zookeeper. Try to delete the job from zookeeper with zkCli.sh. Then deploy the job again on the fixed chronos version. Then start the job and restart chronos to see if it works.

If it still does not work then I'm also not sure. Maybe you can provide the json here and I can try to reproduce...

**Comment by bfoussier** [comment]
Thank you for answer. I am working from main branch, cloned in May.
I have done this fix in function def parse(input: String, timeZoneStr: String = ""): Option[(Long, DateTime, Period)] in file src/main/scala/org/apache/mesos/chronos/scheduler/jobs/Iso8601Expressions.scala

> // we discard R/xxx/P jobs (i.e. forever jobs with 0 period) that makes Chronos falls in infinite loop
> if ((repeatStr.length == 1) && (periodStr.length == 1)) {
> return None
> }

See extract below
  /**
   * Parses a ISO8601 expression into a tuple consisting of the number of repetitions (or -1 for infinity),
   * the start and the period.
   * @param input the input string which is a ISO8601 expression consisting of Repetition, Start and Period.
   * @return a three tuple (repetitions, start, period)
   */
  def parse(input: String, timeZoneStr: String = ""): Option[(Long, DateTime, Period)] = {
    try {

      val iso8601ExpressionRegex(repeatStr, startStr, periodStr) = input

      **// we discard R/xxx/P jobs (i.e. forever jobs with 0 period) that makes Chronos falls in infinite loop
      if ((repeatStr.length == 1) && (periodStr.length == 1)) {
         return None
         }**


      val repeat: Long = {
        if (repeatStr.length == 1)
          -1L
        else
          repeatStr.substring(1).toLong
      }

      val start: DateTime = if (startStr.length == 0) DateTime.now(DateTimeZone.UTC) else convertToDateTime(startStr, timeZoneStr)
      val period: Period = ISOPeriodFormat.standard.parsePeriod(periodStr)
      Some((repeat, start, period))
    } catch {
      case e: scala.MatchError =>
        None
      case e: IllegalArgumentException =>
        None
    }
....


It works :)

**Comment by brndnmtthws** [comment]
It looks like this is no longer necessary.

**Comment by schneidexe** [comment]
@brndnmtthws how you come to that conclusion? Is the part form @bfoussier merged? Othwerise the bug #648 is still valid. An this fix avoids corrupting the data in zookeeper.

**Comment by brndnmtthws** [comment]
I suppose it might still be necessary, but regardless the change needs to be rebased against master before I can merge it.

**Comment by schneidexe** [comment]
Sure, I can do that. So do we reopen it?

**Comment by brndnmtthws** [comment]
Sure let's do it.

**Comment by rbrondgeest** [comment]
So this PR died a silent death and the bug still remains? Can you guys merge this, please?

**Pull request closed without merging**
