### PR TITLE
add UI to display and update following job traits: cpu, mem, disk, prior...

### PR DESCRIPTION
**Pull request by mngo87**
...ity

### CODE REVIEW

**Comment by mngo87** [comment]
New UI
new_resource_ui

Edit screen UI
edit_resource_ui

**Comment by mngo87** [comment]
Exposing some parameters via the UI

**Comment by mngo87** [comment]
@elingg - can you review?

**Comment by elingg** [comment]
@mngo87, very nice! After these UI changes, we probably want to push out another release. I will look at this ASAP.

**Comment by elingg** [comment]
LGTM, any comments @brndnmtthws?

**Comment by brndnmtthws** [comment]
Looks great!

**Comment by ssk2** [comment]
Nice work @mngo87!

**Pull request merged**
