### PR TITLE
Adding description and owner name fields to jobs

### PR DESCRIPTION
**Pull request by aimeemorgan**
This commit adds backend support for job description and owner name fields, plus support for viewing and editing these fields via the Chronos web UI.

Here's a screenshot showing the UI changes:
chronos_ui

### CODE REVIEW

**Comment by mngo87** [comment]
@elingg - can you take a look at this too?

**Comment by elingg** [comment]
LGTM! Any objections @brndnmtthws?

**Comment by mngo87** [comment]
@elingg @brndnmtthws - just bumping so you don't forget.  thanks for reviewing.

**Comment by elingg** [comment]
Looks like no objections from @brndnmtthws so we should be good. One last thing that I forgot to mention, @aimeemorgan. Could you please update the readme?

**Comment by aimeemorgan** [comment]
@elingg Sure. Should I add that commit to this pull request, or open a new one?

**Comment by elingg** [comment]
I would prefer if we also include that in this PR @aimeemorgan.

**Comment by aimeemorgan** [comment]
@elingg Added a commit with the readme updates.

**Comment by elingg** [comment]
:+1:

**Pull request merged**
