### PR TITLE
better task id

### PR DESCRIPTION
**Pull request by whua-airbnb**
@airbnb/di 
A better tasked so that is avoid the namespace conflict of ":". It also makes the time stamp more readable.

### CODE REVIEW

**Comment by brndnmtthws** [comment]
@elingg Any thoughts before merging?

**Comment by elingg** [comment]
LGTM. ":" is sometimes used as a delimiter (i.e. docker) so I'm glad to see this fix.

**Comment by elingg** [comment]
@whua-airbnb, @brndnmtthws, this has been idle for some time. Any objections to closing this?

**Comment by brndnmtthws** [comment]
@elingg No objections here.

@whua-airbnb Please feel free to update against master, and re-open the PR if you'd like.

**Pull request closed without merging**
