### PR TITLE
Disable flakey test

### PR DESCRIPTION
**Pull request by BenWhitehead**

### CODE REVIEW

**Comment by BenWhitehead** [comment]
@elingg @brndnmtthws Can either of you merge this PR?

This flakey test is blocking @lingmann getting new packages out.

**Comment by brndnmtthws** [comment]
Do you have a log of the failure?

**Comment by BenWhitehead** [comment]
Here is a link to all the build failures jeremy ran into.

https://teamcity.mesosphere.io/viewType.html?buildTypeId=Oss_Chronos_MakeDistroPackage_2&tab=buildTypeHistoryList&branch_Oss_Chronos=__all_branches__

**Comment by brndnmtthws** [comment]
I'd like to figure out *why* it failed, and after investigating for a bit, it's not clear what the cause is. I'm not opposed to merging this if that's what's needed to move things forward.

**Comment by BenWhitehead** [comment]
True I think this should be tracked down, however the workaround that was in place before was to disable all tests.  It's better to have one disabled test then not run any at all.  I don't know what would be involved in tracking down and fixing this test, I opened the PR to help remove the blocker for @lingmann.

**Comment by elingg** [comment]
@benwhitehead, give me a few to investigate

**Comment by brndnmtthws** [comment]
I've been running this test in a loop on my laptop for about an hour now, without any errors. Something is fishy.

**Comment by elingg** [comment]
Same here, I can't recreate the problem on my laptop. It could be a difference in some state configuration on the teamcity environment, possibly related to zookeeper. It seems maybe the test isn't well written, but I would like to track down why.

**Comment by elingg** [comment]
Debugged the issue. The test was using a ScheduledThreadPool as a listener which was not working in all build environments.. I will be creating a PR to fix the test so I will close this PR. Thanks!

**Pull request closed without merging**
