### PR TITLE
Redo internal scheduling codes.

### PR DESCRIPTION
**Pull request by brndnmtthws**
- Never skip a job (removed concepts of 'epsilon' and 'scheduler
   horizon')
 - Scheduler now has a simple pattern of sleeping until it's time to
   execute a scheduled job, and queueing it at that time
 - Removed a bunch of apparently pointless code
 - Dropped concept af 'async' jobs

### CODE REVIEW

**Comment by Rob-Johnson** [comment]
@brndnmtthws is there a ticket or something associated with this?

**Comment by brndnmtthws** [comment]
@Rob-Johnson

Hey Rob,

We have some internal JIRAs for these issues, but I'm not sure about here on GitHub. The tl;dr is that there are some known issues and limitations in how chronos does scheduling, and I feel the best way to resolve these issues is to fix the core scheduling code.

There's more work to come. This is still a work in progress. I can CC you on the follow up PRs if you'd like.

**Comment by Rob-Johnson** [comment]
@brndnmtthws 

That'd be good. I've been actively working on our fork at [Yelp/chronos](github.com/Yelp/chronos) - such sweeping changes that come without warning make it difficult to make sure changes we make can be contributed back upstream. Saying that, It's promising that there is some effort being put into Chronos again.

**Comment by solarkennedy** [comment]
As an update, we are no longer using Chronos at Yelp. We will be archiving our fork of Chronos.

**Pull request merged**
