### PR TITLE
expose more job variables via yaml files

### PR DESCRIPTION
**Pull request by mngo87**
Expose more variables to yaml file, to allow an user to have more control over job management.

### CODE REVIEW

**Comment by elingg** [comment]
LGTM, any comments @brndnmtthws ?

**Comment by brndnmtthws** [comment]
These fields were intentionally dropped. At the very least, it should ignore the `disabled` field because we don't want to re-enable jobs which were disabled due to failures (that defeats the purpose of the disable-after-N-failures feature).

The other fields were found to be more harm than good when modified, and thus were dropped. I'd be willing to include them back if necessary.

**Comment by mngo87** [comment]
@brndnmtthws that makes sense in regards to disabled, I can remove that field.  The main fields that I want to update are epsilon and retries.  What are your thoughts on the other fields?  I don't see any harm keeping the async field as well.

**Comment by brndnmtthws** [comment]
Yeah, it's reasonable. These things may be dropped in future releases (particularly the async mode), just FYI.

**Pull request merged**
