### PR TITLE
Support disabling prompt for deleting missing jobs

### PR DESCRIPTION
**Pull request by sdwr98**
We have an automated script that generates chronos jobs and syncs them with Chronos.  We'd like to be able to delete missing jobs without the prompt.

### CODE REVIEW

**Comment by elingg** [comment]
This seems like a reasonable option to me and looks good, although it is adding more complexity to the script. Ideally, we would modularize this script and break it down some. Any objections @brndnmtthws?

**Comment by brndnmtthws** [comment]
How about just reuse the `-f` flag for this purpose?

**Comment by sdwr98** [comment]
@brndnmtthws I actually thought the first time that I used it that `-f` implied `--delete-missing`.  What are your thoughts on making that change? Or I can make it so that -f replaces the no-prompt option.

**Comment by brndnmtthws** [comment]
I think just updating the docs (and code) to reflect that `-f` means no prompt on delete should be sufficient.

**Comment by sdwr98** [comment]
@brndnmtthws @elingg Updated to use -f instead of another flag. Thanks!

**Comment by brndnmtthws** [comment]
Looks nice, thanks! Has it been tested?

**Comment by sdwr98** [comment]
Yes, it has.  Without --force it retains the current behavior, with --force it just issues the DELETE.

**Pull request merged**
