### PR TITLE
Add support for docker_force_pull (#345)

### PR DESCRIPTION
**Pull request by hermansc**
Fixes issue #345 .

### CODE REVIEW

**Comment by elingg** [comment]
Thanks, @hermansc! The build does need to pass though.

**Comment by hermansc** [comment]
Yeah, sorry for that. I had to leave in a hurry. Keep an eye out for a proper commit tomorrow.

**Comment by hermansc** [comment]
There :+1:

**Comment by brockoffdev** [comment]
This is a great add, thanks @hermansc

**Comment by elingg** [comment]
Awesome!

**Comment by elingg** [comment]
@hermansc Could you update the container field in the "Job Configuration" section of the API? It should say "This contains the subfields for the container, type (req), image (req), forcePullImage (optional), network (optional), and volumes (optional)." Then we should be good to :shipit:

**Comment by hermansc** [comment]
Oh yes, of course. Didn't see that. Added info under "Job Configuration" and "Adding a scheduled job".

**Pull request merged**
