### PR TITLE
Added Overview to doc table of contents

### PR DESCRIPTION
**Pull request by joel-hamill**
This will allow Overview to show in main doc view, along with getting started.

### CODE REVIEW

**Comment by aquamatthias** [comment]
Thanks @joel-hamill

**Comment by elingg** [comment]
Should we also merge this change into the gh-pages branch or was this already done, @aquamatthias / @joel-hamill ?

**Comment by joel-hamill** [comment]
@elingg I think we should. Is there additional action I need to take?

**Comment by elingg** [comment]
@joel-hamill, Yes, you need to check in those changes to the gh-pages branch. Glad to help or @ssk2 or @aquamatthias can show you.

**Pull request merged**
