### PR TITLE
Fix: cleaning invalid task with a wrong task name

### PR DESCRIPTION
**Pull request by depay**
Func removeTask uses task name without prefix "T_".

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Looks reasonable. Have you tested this?

**Comment by depay** [comment]
@brndnmtthws  Tested.

**Comment by elingg** [comment]
@depay, Could you put val taskId = f.substring(taskPrefix.size) above the if statement so taskId can be used here to make the code cleaner?

**Comment by elingg** [comment]
:+1:

**Pull request merged**
