### PR TITLE
Add port mappings

### PR DESCRIPTION
**Pull request by bengunter**
I based my changes off of 2.4.0 because that's the version we're using, and we needed this feature immediately.

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Can you rebase against master please?

**Comment by andrebeat** [comment]
I think it would be cool if this also supported setting randomly assigned ports like in marathon (and especially keeping the same random port inside and outside the container) [[1]](https://mesosphere.github.io/marathon/docs/native-docker.html#bridged-networking-mode). Additionally, in order for this to be useful the assigned port should be exposed to the container (again like in marathon [[2]](https://mesosphere.github.io/marathon/docs/task-environment-vars.html#host-ports)).

**Comment by brndnmtthws** [comment]
Could you rebase against master?

**Comment by brndnmtthws** [comment]
I'm closing this PR for now. If you'd like to rebase against master and reopen, feel free.

**Comment by bengunter** [comment]
@brndnmtthws We've moved to Singularity so I won't be following up on this. The code is here if anyone else wants to use it.

**Pull request closed without merging**
