### PR TITLE
WIP - Unified containers, cni networks and persistent/external volumes support.

### PR DESCRIPTION
**Pull request by vixns**
New features require mesos >= 1.0.0-rc1, should be compatible with mesos  >= 0.28 (not tested)
- Current limitations:
  - Lack APPC images support.
  - Lack image credential support.
  - WIP, need tests and documentation.

sample : 

``` json
{
  "schedule": "R/2016-01-01T00:00:00Z/PT1M",
  "name": "test",
  "container": {
    "type": "MESOS",
    "forcePullImage": true,
    "image": "debian",
    "networkName": "mynet",
    "volumes": [
      {
        "mode": "RW",
        "containerPath": "/tmp",
        "external": {
          "name": "test",
          "provider": "local-persist",
          "options": [
            {
              "key": "mountpoint",
              "value": "/tmp/test"
            }
          ]
        }
      },
      {
        "mode": "RW",
        "containerPath": "testp",
        "persistent": {
          "size": 100
        }
      }
    ]
  },
  "cpus": "0.1",
  "mem": "32",
  "command": "date"
}
```

### CODE REVIEW

**Comment by soualid** [comment]
Nice !

**Comment by epchris** [comment]
Any updates on this? This seems like a very useful addition with the new [unified containerizer](http://mesos.apache.org/documentation/latest/container-image/) effort in Mesos.

Are the changes to the Dockerfile and start scripts necessary?  No offense intended, but I'm not sure it makes sense to have the "official" Chronos docker image be based on your base docker image rather than something like ubuntu LTS.

**Comment by vixns** [comment]
Mesos 1.0.0 was not yet available in the mesosphere repository, that's why we used a custom image. I will revert theses changes and update the dependencies ASAP.

**Comment by epchris** [comment]
Awesome, I'm excited to see this functionality get included!

**Comment by brndnmtthws** [comment]
Could you rebase against master?

**Comment by brndnmtthws** [comment]
I'm closing this PR for now. If you'd like to rebase against master and reopen, feel free.

**Pull request closed without merging**
